services:
  - type: web
    name: wb-price-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: RENDER_EXTERNAL_URL
        value: https://your-service-name.onrender.com
      - key: WEBHOOK_SECRET
        value: your_secure_secret_here
