services:
  - type: web
    name: wb-price-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8399639689:AAFBQwqm06GVoAdTH6N_0ecqgjQ_cmyiEMU
      - key: PORT
        value: 8080
    ports:
      - port: 8080
        protocol: http
        isHttps: false
